#! /bin/bash

# TODO: Use amixer rather than /proc to determine mute status

VOL=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")
if [ "$VOL" -eq 0 ]; then
 echo "MUTE"
else
 echo "VOL : $VOL"
fi

