[env]
TERM = "alacritty"

[window]
title = "Alacritty"
dynamic_title = true
opacity = 0.88
decorations = "full"

[window.padding]
x = 8
y = 8

[font]
size = 7.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[colors.primary]
background = "#000000"
foreground = "#dcdccc"

[colors.cursor]
cursor = "#00cccc"
text = "#000000"

[colors.selection]
background = "#00aaaa"
text = "#1c1c1c"

[colors.normal]
black   = "#1c1c1c"
red     = "#704040"
green   = "#339999"
yellow  = "#aaaa66"
blue    = "#228888"
magenta = "#448888"
cyan    = "#00aaaa"
white   = "#dcdccc"

[colors.bright]
black   = "#3a3a3a"
red     = "#cc6666"
green   = "#44dddd"
yellow  = "#ffffaf"
blue    = "#33cccc"
magenta = "#66d9cc"
cyan    = "#00ffff"
white   = "#ffffff"

[cursor]
style = "Beam"
unfocused_hollow = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
